name: full_leads_v01
description: "Full Leads App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_secure_storage:
  http: ^1.4.0
  mobile_scanner: ^7.0.0
  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - .env
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 100